OBJS = lexico.cpp automato.cpp main.cpp

CC = g++

COMPILER_FLAGS = 

LINKER_FLAGS = -std=c++11

OBJ_NAME = l9e1

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

clean:
	rm -f $(OBJ_NAME)
